### ISSUE TITLE
Tusky v22 release tracker

### ISSUE THREAD

**Issue by nikclayton** [tuskyapp/Tusky#3551]
Tracking the work to perform the v22 release. Unless anything unexpected occurs, the release process will start 2023-4-24.

Current state: Beta 7 is released, with no reported problems. Preparing the final release.

# Known issues

## From beta 1

- [x] Reports of notifications feeling slow to load
  - Samples:
    - https://github.com/tuskyapp/Tusky/issues/3578
    - https://iscurrently.live/@theresnotime/110265680543801379
  - Probably due to the increase in the number of initial notifications loaded
  - https://github.com/tuskyapp/Tusky/pull/3598 is the fix
- [x] IndexOutOfBoundsException saving the Notification reading position
  - Fix: https://github.com/tuskyapp/Tusky/pull/3581
- [ ] https://github.com/tuskyapp/Tusky/pull/3583
- [x] Pixelfed notifications no longer work, https://github.com/tuskyapp/Tusky/issues/3580
  - Not planned to be fixed
- [x] https://github.com/tuskyapp/Tusky/issues/3588
  - https://github.com/tuskyapp/Tusky/pull/3590
- [x] https://github.com/tuskyapp/Tusky/issues/3587
  - https://github.com/tuskyapp/Tusky/pull/3589
- [x] https://github.com/tuskyapp/Tusky/pull/3594
- [x] https://github.com/tuskyapp/Tusky/pull/3597
- [x] https://github.com/tuskyapp/Tusky/pull/3603
- [x] Incorrect clickable areas in some statuses
  - Fix: https://github.com/tuskyapp/Tusky/pull/3600
- [x] Show FAB in correct location when listing filters
  -https://github.com/tuskyapp/Tusky/pull/3561
- [x] https://github.com/tuskyapp/Tusky/pull/3609
- [x] Reporting posts was inadvertently broken
  - https://github.com/tuskyapp/Tusky/pull/3607

## From beta 2

- [x] https://github.com/tuskyapp/Tusky/pull/3622
- [x] https://github.com/tuskyapp/Tusky/pull/3614
- [x] https://github.com/tuskyapp/Tusky/pull/3612
- [ ] https://github.com/tuskyapp/Tusky/pull/3626
- [x] https://github.com/tuskyapp/Tusky/pull/3634

# PRs to review and merge pre-release process start

- [x] https://github.com/tuskyapp/Tusky/pull/3513
- [x] https://github.com/tuskyapp/Tusky/pull/3514
- [x] https://github.com/tuskyapp/Tusky/pull/3281
- [x] https://github.com/tuskyapp/Tusky/pull/3521
- [x] https://github.com/tuskyapp/Tusky/pull/3510
- [x] https://github.com/tuskyapp/Tusky/pull/3421
- [x] https://github.com/tuskyapp/Tusky/pull/3556
- [x] https://github.com/tuskyapp/Tusky/pull/3557
- [x] https://github.com/tuskyapp/Tusky/pull/3559
- [x] Any translations

# Issues to review pre-release process start

- [x] https://github.com/tuskyapp/Tusky/issues/3550

# Release steps

Following https://github.com/tuskyapp/Tusky/blob/develop/Release.md

## v22.0 beta 1

- [x] Prep the beta release code changes, https://github.com/tuskyapp/Tusky/pull/3567
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid. [Example](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11218) (F-Droid automatically picks up new release tags, but not beta ones. This could probably be changed somehow.)
  - [x] It's been merged
- [x] Announce the release

## v22.0 beta 2

- [x] Prep the beta release code changes, https://github.com/tuskyapp/Tusky/pull/3611
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.2
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid. [Example](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11218) (F-Droid automatically picks up new release tags, but not beta ones. This could probably be changed somehow.)
  - [x] https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13033
  - [ ] It's been merged
- [x] Announce the release

## v22.0 beta 3

- [x] Prep the beta release code changes, https://github.com/tuskyapp/Tusky/pull/3656
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.3
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid. [Example](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11218) (F-Droid automatically picks up new release tags, but not beta ones. This could probably be changed somehow.)
  - [x] It's been merged
- [x] Announce the release

## v22.0 beta 4

- [x] Prep the beta release code changes, https://github.com/tuskyapp/Tusky/pull/3664
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.4
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid. [Example](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11218) (F-Droid automatically picks up new release tags, but not beta ones. This could probably be changed somehow.)
  - [x] https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13092
  - [x] It's been merged
- [x] Announce the release

## v22.0 beta 5

- [x] Prep the beta release code changes
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.5
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid. [Example](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/11218) (F-Droid automatically picks up new release tags, but not beta ones. This could probably be changed somehow.)
  - https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13107
  - [x] It's been merged
- [x] Announce the release

## v22.0 beta 6

- [x] Prep the beta release code changes
- [x] Merge code changes to `develop`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.6
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid.
  - https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13147
  - [x] It's been merged
- [x] Announce the release

## v22.0 beta 7

- [x] Prep the beta release code changes, https://github.com/tuskyapp/Tusky/pull/3710
- [x] Merge code changes to `main`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0-beta.6
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [x] Create a merge request at F-Droid.
  - https://gitlab.com/fdroid/fdroiddata/-/merge_requests/13147
  - [x] It's been merged
- [x] Announce the release

## v22.0 final

- [x] Prep the release code changes, https://github.com/tuskyapp/Tusky/pull/3718
- [x] Merge code changes to `main`
- [x] Merge and create GitHub release, https://github.com/tuskyapp/Tusky/releases/tag/v22.0
- [x] Confirm that Bitrise has built and uploaded the release to the Internal Testing track on Google Play.
- [x] Do a quick check to make sure the build doesn't crash, e.g. by enrolling yourself into the test track.
    - In case there are any problems, delete the GitHub release, fix the problems and start again
- [x] Download the build as apk from Google Play (App Bundle Explorer -> chose the release -> Downloads -> Signed, universal APK). Attach it to the GitHub Release.
- [x] Create a new Open Testing release on Google Play. Reuse the build from the Internal Testing track.
- [ ] Create a merge request at F-Droid.
  - [ ] It's been merged
- [ ] Announce the release

**Comment by connyduck** [comment]
No critical bug reports via Mastodon so far https://chaos.social/@ConnyDuck/110232661739967318

**Comment by nikclayton** [comment]
I'm going to use this comment (i.e., I'll edit it semi-frequently) to note things to change in the release process documentation.

- [ ] Release owner needs access to `@tusky@mastodon.social` DMs to review problem reports
- [ ] Release owner needs access to Weblate console (?)

**Comment by connyduck** [comment]
https://github.com/tuskyapp/Tusky/pull/3594

**Comment by timnolte** [comment]
I'm experiencing nothing but crashes on the latest beta on all feeds except Notifications/Mentions. All attempts to fix the issue short of completely wiping the app storage doesn't fix the issue. I'm not sure if this would be related to one of the existing crash items? I submitted a crash report after the app kept crashing, I'm not sure if these actually make it to the Devs or just Google.

**Comment by nikclayton** [comment]
@timnolte: Which server are you on?

There's an uptick in crashes involving JSON parsing, but they don't include whatever the malformed JSON is, so it's difficult to track down at the moment.

If I provided some debugging instructions that involved using Chrome's network inspector, would you be able to carry them out?

**Comment by timnolte** [comment]
> @timnolte: Which server are you on?
> 
> There's an uptick in crashes involving JSON parsing, but they don't include whatever the malformed JSON is, so it's difficult to track down at the moment.
> 
> If I provided some debugging instructions that involved using Chrome's network inspector, would you be able to carry them out?

@nikclayton I'm on my own single user instance. Yeah, if you have some debugging instructions I can do some digging. What's interesting is that somehow after a period of time, perhaps after a background feed update, it stopped crashing.

**Comment by nikclayton** [comment]
> @nikclayton I'm on my own single user instance. Yeah, if you have some debugging instructions I can do some digging. What's interesting is that somehow after a period of time, perhaps after a background feed update, it stopped crashing.

OK. https://github.com/tuskyapp/Tusky/pull/3610/commits/2eb7122b026853638fa7a4d559db4aafcd7844cc?short_path=00c65c2#diff-00c65c2349f395f9f9b78b0fe84d3638b78f3ef4abf98294364b5c4d0ef32473 explains how to get your bearer token and construct API requests.

My working theory is that some post in your home timeline contains a status that is being represented in JSON that doesn't match the expectations in the code.

For example, if you clear the Tusky cache (Android App Info, Storage & Cache > Clear storage), restart Tusky, log in, and the crash happens that would certainly point in that direction.

To check that, the JSON response for an API request to `https://[yourserver]/api/v1/timelines/home` would be very helpful. If you could attach it as a file to this issue that would be great.

Please be careful to redact any information you don't want to share from the JSON before sharing, but please don't remove content, just replace strings with e.g., a run of `a` of the same length, numbers with a run of `1` of the same length.

**Comment by timnolte** [comment]
> @timnolte What server software and version are in use on your instance?

@Tak my instance is running on Ubuntu 22.04 on arm64 running Mastodon 4.1.2.

**Comment by timnolte** [comment]
@nikclayton what you describe makes a lot of sense, and I sort of wondered if it was hitting a certain post causing problems. As of right now I think my Home feed must have moved past the offending post(s) and so Tusky is working again. I'll keep looking out for another round of crashes and grab a sample for you with hopefully something useful.

**Comment by timnolte** [comment]
@nikclayton OK, so Tusky just started crashing again a bit ago. I just now was able to make a request to my instance and I've included the JSON response here:

https://gist.github.com/timnolte/052de6b0e2ca208624b6070d59c6c443

I didn't see anything sensitive in my timeline there so I didn't redact anything. I'm not 100% sure if the offending item in my home feed was returned in that request or not.

**Comment by timnolte** [comment]
@nikclayton here is screenshot of what's in my timeline before Tusky closes.

![image](https://user-images.githubusercontent.com/4312062/236064029-f539ab33-5a0f-4927-aa8c-d01c071d4f4a.png)

I'm wondering about that second post as there are perhaps some bad UTF8 encoded quotes I'm noticing in that post. Wondering it we have a quote escaping issue here?

**Comment by timnolte** [comment]
@nikclayton so, that may not be it. I just tried to open it and it refreshed and started working with those 2 posts showing and the Load More about them. 🤷🏼

**Comment by timnolte** [comment]
@nikclayton OK, new sort of thing happening. My home feed is working just fine however, trying to open my Hashtags feed, DMs, or notifications, are all crashing now. :-/

**Comment by nikclayton** [comment]
@timnolte Which tabs do you have configured, and what order are they on the timeline? https://github.com/tuskyapp/Tusky/pull/3609 just got merged (and will be in beta 2) that was a crash I don't follow understand when navigating through tabs.

**Comment by timnolte** [comment]
@nikclayton here is my setup. App is crashing again when loading the Home feed again.

![Screenshot_20230504-222737.png](https://user-images.githubusercontent.com/4312062/236366203-414a1176-ba99-4168-bff2-db28cbdcdda5.png)

**Comment by nikclayton** [comment]
@timnolte crashing with beta 1 or beta 2?

**Comment by timnolte** [comment]
> @timnolte crashing with beta 1 or beta 2?
> 
> edit: I tested https://gist.github.com/timnolte/052de6b0e2ca208624b6070d59c6c443, that parses with no problems

@nikclayton I'm running beta 2.

**Comment by nikclayton** [comment]
@timnolte OK. I'm going to write a dedicated crash handler so I can more data. Are you comfortable sideloading a custom build of Tusky with some additional crash detection logic (https://www.xda-developers.com/how-to-sideload-install-android-app-apk/) ?

**Comment by nikclayton** [comment]
> > @timnolte OK. I'm going to write a dedicated crash handler so I can get more data. Are you comfortable sideloading a custom build of Tusky with some additional crash detection logic (https://www.xda-developers.com/how-to-sideload-install-android-app-apk/) ?
> 
> @nikclayton yeah, I can do that.

@timnolte OK, try the attached. It's only zipped because GitHub doesn't allow APK as a file type for attachments.

This is beta 2 + the code in https://github.com/tuskyapp/Tusky/pull/3628 (that PR has a screenshot of what you should see when it crashes). It'll install as a Tusky Nightly build, so it won't interfere with your existing installation of beta 2.

The JSON file contains some metadata about the Tusky build, a stack trace for the crash, and the last 5 requests/responses Tusky made to the Mastodon API (in order oldest to newest). We probably only need the most recent one, but better to be safe than sorry.

Hopefully this help nail whatever this problem is to the wall.

[Tusky_22.0 beta 2-58034dbc_104_58034dbc_green_debug.zip](https://github.com/tuskyapp/Tusky/files/11410220/Tusky_22.0.beta.2-58034dbc_104_58034dbc_green_debug.zip)

**Comment by timnolte** [comment]
@nikclayton so I side loaded the APK, added my Mastodon instance/account. The app looks to load my Home feed but then just freezes and I keep getting a close or wait dialog.

**Comment by nikclayton** [comment]
Weirder and weirder.

1. Does the official Mastodon app work with your account?
2. If you create a second account on your server, does Tusky work with that account?
3. Can you get the Tusky logs from the device?

For that last one you will need to:

1. Follow the instructions at https://source.android.com/docs/setup/build/adb to download adb (Android Debug Bridge) to a computer you can connect your phone to.
2. Enable USB debugging on your device (https://developer.android.com/tools/adb#Enabling)
3. Connect your phone. You should see a dialog that asks if you want to enable USB debugging for the computer you just connected it to. Accept this.
4. Run the following command to find the user ID of the APK from two comments up:
  - Mac / Linux: `adb shell dumpsys package com.keylesspalace.tusky.test | grep userId`
  - Windows: `adb shell dumpsys package com.keylesspalace.tusky.test | FINDSTR userId`
  - You should see output like `userId=10146` (your number will differ)
5. Run `adb logcat -f crash_tusky_test.log --uid=$UID` (use whatever `userId` was printed at the previous step
6. Run the test version of Tusky from the APK I gave you (green Tusky icon), wait for it to crash
7. Stop the `adb logcat` command.
8. Check the `crash.log` file, make sure it doesn't contain any information you don't want to disclose. If it does, redact
9. Attach it to a comment

You could also repeat steps 4-9, but change the package name to `com.keylesspalace.tusky` (i.e., no `.test` at the end). That will give you a different user ID value. Re-run the `adb logcat` but send the output to `crash_tusky.log`. Then run Tusky beta 2 (blue Tusky icon), and interact with it until it crashes.

**Comment by timnolte** [comment]
> Weirder and weirder.
> 
> 1. Does the official Mastodon app work with your account?

So that's the thing, because of these recent issues I started using the Megalodon app, which is a fork of the official Mastodon app, and it works without problems. The other interesting thing is that I got notifications from the nightly build and when I opened those, which took me to that tab, the app was working fine for all tabs except for the Home tab which just froze again and then closed.

**Comment by nikclayton** [comment]
I'm going to need logs to debug this any further. Can you try the steps above? Alternatively, can I create an account on your server, and seed it with a list of the same people you're following, so I get the same experience?

**Comment by timnolte** [comment]
Yeah, I'll get you some logs tonight.

**Comment by timnolte** [comment]
@nikclayton here are the crash logs:

- https://gist.github.com/timnolte/240c80b033beca2fbad98e8e33904123
- https://gist.github.com/timnolte/688b7f0b1633813e6405356b76c4b70b

**Comment by nikclayton** [comment]
Smoking gun:

05-01 18:40:34.337 18427 18427 E AndroidRuntime: com.google.gson.o: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 159960 path $[18].filtered[0].status_matches

Code is:

```
data class FilterResult(
    val filter: Filter,
    @SerializedName("keyword_matches") val keywordMatches: List<String>?,
    @SerializedName("status_matches") val statusMatches: String?
)
```

API docs (https://docs.joinmastodon.org/entities/FilterResult/#status_matches) say that this is a nullable string, which matches the Tusky code.

But the example on the same page shows it as an array of string.

```
...
  "status_matches": [
    "109031743575371913"
  ]
...
```

**Comment by nikclayton** [comment]
I've filed a bug (linked above) with the Mastodon folks to find out what this is supposed to be.

The official Mastodon app doesn't have this problem because it doesn't support this new feature, and I suspect it's the same for Megalodon.

**Comment by nikclayton** [comment]
https://github.com/tuskyapp/Tusky/pull/3634 <-- temporary fix

**Comment by nikclayton** [comment]
@timnolte Here's beta 2 with the fix from #3634 applied. Can you try it and see if it fixes the problem?

[Tusky_22.0 beta 2-63d000d4_104_63d000d4_green_debug.zip](https://github.com/tuskyapp/Tusky/files/11421036/Tusky_22.0.beta.2-63d000d4_104_63d000d4_green_debug.zip)

**Comment by timnolte** [comment]
@nikclayton just confirming that the last beta you sent me is working great, while the current beta still crashes. Seems like that issue you opened with Mastodon is for sure the culprit.

**Comment by nikclayton** [comment]
@timnolte Thanks for the confirmation.

**Comment by nikclayton** [comment]
Last steps are:

1. Merge https://github.com/tuskyapp/tuskyapp.github.io/pull/17
2. Update page on opencollective
